/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#3b82f6',
          'primary-content': '#ffffff',
          secondary: '#64748b',
          'secondary-content': '#ffffff',
          accent: '#8b5cf6',
          'accent-content': '#ffffff',
          neutral: '#1f2937',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f3f4f6',
          'base-300': '#e5e7eb',
          'base-content': '#1f2937',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#10b981',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#ffffff',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
        dark: {
          ...require('daisyui/src/theming/themes')['dark'],
          primary: '#60a5fa',
          'primary-content': '#000000',
          secondary: '#94a3b8',
          'secondary-content': '#000000',
          accent: '#a78bfa',
          'accent-content': '#000000',
          neutral: '#374151',
          'neutral-content': '#d1d5db',
          'base-100': '#1f2937',
          'base-200': '#111827',
          'base-300': '#0f172a',
          'base-content': '#f3f4f6',
          info: '#60a5fa',
          'info-content': '#000000',
          success: '#34d399',
          'success-content': '#000000',
          warning: '#fbbf24',
          'warning-content': '#000000',
          error: '#f87171',
          'error-content': '#000000',
        },
      },
    ],
  },
};
